### ISSUE TITLE
Could not pip install had to move files

### ISSUE THREAD

**Issue by EHYPI** [pierrebaudot/infotopopy#4]
In order for setup.findpackages to find packages during install I had to move __init__.py and infotopo.py to a separate folder named "infotopo". Installing from tar.gz or the PyPi archive does not work.

**Comment by renxida** [comment]
I submitted a pull request to fix this.

For now, CornJojk, you may try: `python -m pip install git+https://github.com/renxida/infotopopy`

**Comment by pierrebaudot** [comment]
Thank you Renxida for your effort
